name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.docker_repository}}:$(date +%s)
    - name: Push the Docker image
      run: |
        docker login ${{ secrets.docker_username}} -p ${{ secrets.docker_secret }}
        docker push ${{ secrets.docker_repository}}

