name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.docker_repository}}:$(date +%s)
        echo ${{ secrets.docker_secret }} | docker login --username ${{ secrets.docker_username }} --password-stdin
        docker push ${{ secrets.docker_repository}}

